MVC_LMS/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLayer.Models;
using BusinessLayer;
using System.Threading.Tasks;
using Newtonsoft.Json;
using MVC_LMS.Models;

namespace MVCLayer.Controllers
{
    public class LoginController : Controller
    {

        // GET: Login
        public ActionResult Index()
        {

            this.Session["token"] = "i was called";
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Index(LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {

                LoginBL loginBL = new LoginBL();
                loginModel.grant_type = "UserPassword";

                string request = JsonConvert.SerializeObject(loginModel);
                string token = await loginBL.Login(request);
                MyAccessToken myToken = JsonConvert.DeserializeObject<MyAccessToken>(token);
                Session["token"] = myToken.access_token;
                Session["loggedIn"] = "true";
                Session["UserName"] = loginModel.UserName;
                StudentBL studentBL = new StudentBL();
                string Users = await studentBL.GetStudents();
                List<User_Details> user = JsonConvert.DeserializeObject<List<User_Details>>(Users);
                foreach (User_Details u in user)
                {
                    if (u.UserName == loginModel.UserName && u.Category == "Admin")
                    {
                        return RedirectToAction("Index", "AdminHome");
                    }
                    else if (u.UserName == loginModel.UserName && u.Category == "Student")
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                return RedirectToAction("Error", "Login");
            }
            return View("Index");
        }

        public ActionResult Error(string response)
        {
            ViewBag.response = response;
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return View();
        }
    }
}

MVC_LMS/Controllers/RegistrationController.cs
using BusinessLayer;
using MVC_LMS.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVC_LMS.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(User_Details u)
        {
            RegistrationBL reg = new RegistrationBL();
            string student = JsonConvert.SerializeObject(u);
            string result = await reg.Register(student);
            if (result == "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

MVC_LMS/Views/Login/Index.cshtml
@model MVCLayer.Models.LoginModel

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.grant_type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.grant_type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.grant_type, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("New Registration", "Create", "Registration")
</div>

MVC_LMS/Views/Login/Logout.cshtml
@{ ViewBag.Title = "Logout"; }



<h2 class="col-lg-6 col-lg-offset-3">You have been successfully logged out.</h2>
<br />
<br />
@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{
<button class="btn btn-default col-lg-2 col-lg-offset-5" type="submit">Go Back To Home</button>}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />